# Generated by Django 4.2.2 on 2023-06-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0002_teammembers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teammembers", old_name="desc", new_name="desc1",
        ),
        migrations.RenameField(
            model_name="teammembers", old_name="img", new_name="img1",
        ),
        migrations.RenameField(
            model_name="teammembers", old_name="name", new_name="name1",
        ),
    ]
