# Generated by Django 4.2.2 on 2023-06-20 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0003_rename_desc_teammembers_desc1_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="Place",),
        migrations.RenameField(
            model_name="teammembers", old_name="desc1", new_name="desc",
        ),
        migrations.RenameField(
            model_name="teammembers", old_name="img1", new_name="img",
        ),
        migrations.RenameField(
            model_name="teammembers", old_name="name1", new_name="name",
        ),
    ]
