# Generated by Django 4.2.2 on 2023-07-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0004_delete_place_rename_desc1_teammembers_desc_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("img", models.ImageField(upload_to="pics")),
                ("desc", models.TextField()),
            ],
        ),
    ]
